name: Terraform
on:
  push:
    branches: main
  workflow_dispatch:
jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      TF_VAR_billing_account: '${{ secrets.TF_VAR_billing_account }}'
      TF_VAR_org_id: '${{ secrets.TF_VAR_org_id }}'
    steps:
    - name: Check out repository code
      uses: actions/checkout@v4
    - name: Authenticate with Google Cloud
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
    - name: Terraform fmt
      id: fmt
      run: terraform fmt -check
      continue-on-error: true
    - name: Terraform Init
      id: init
      run: terraform init
    - name: Terraform Plan
      id: plan
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: terraform plan
    - name: Terraform Apply
      id: apply
      if: github.event_name == 'workflow_dispatch'
      run: terraform apply
    - name: Terraform Show
      id: show
      run: terraform show
